### ISSUE TITLE
Security Issue (Paypal, gmail)

### ISSUE THREAD

**Issue by ousamabenyounes** [TranscodeFiles/WEB-APP#2]
Hi

@PaphaC @aymericDD @lauzel @etienne-me @GBenoitG 

You have a your paypal, gmail credentials on your https://github.com/TranscodeFiles/WEB-APP/blob/master/app/config/config.yml file

Remove them correctly from github: https://help.github.com/articles/removing-sensitive-data-from-a-repository/
if you just commit an update, we'll be able to view them on your history so the problem won't be fixed.
Hackers looks on your git history to get credentials information

To help you fix symfony project problem I recommand you to plug it to:
https://insight.sensiolabs.com

Free for open source project :)

Regards,
Ousama.

**Comment by e-gautier** [comment]
Thanks. These are actually fake accounts.

**Comment by aymericDD** [comment]
Hi @ousamabenyounes,

Thanks for your feedback. 😄 
We have removed all history of configuration file and its sensitive data.

Free for open source project !! :v:

Best regards,
Aymeric.
